export default[
    {"name": "Alexandria"},
    {"name": "Aswan"},
    {"name": "Asyut"},
    {"name": "Beheira"},
    {"name": "Beni Suef"},
    {"name": "Cairo"},
    {"name": "Dakahlia"},
    {"name": "Damietta"},
    {"name": "Faiyum"},
    {"name": "Gharbia"},
    {"name": "Giza"},
    {"name": "Ismailia"},
    {"name": "Kafr El Sheikh"},
    {"name": "Luxor"},
    {"name": "Matrouh"},
    {"name": "Minya"},
    {"name": "Monufia"},
    {"name": "New Valley"},
    {"name": "North Sinai"},
    {"name": "Port Said"},
    {"name": "Qalyubia"},
    {"name": "Qena"},
    {"name": "Red Sea"},
    {"name": "Sharqia"},
    {"name": "Sohag"},
    {"name": "South Sinai"},
    {"name": "Suez"}
]
  